### ISSUE TITLE
Time zone used in app differs to timezone used in ERP Next

### ISSUE THREAD

**Issue by vikineema** [kartoza/timesheet-project#102]
There is a one hour difference between the time recorded using the timesheet app and the time pushed to the erpnext timesheets. 
![image](https://github.com/kartoza/timesheet-project/assets/39700992/8d37587c-1a1b-47ed-95a7-7fbd1c641efb)

![image](https://github.com/kartoza/timesheet-project/assets/39700992/215bfd7a-93ea-4a20-833f-b24bb55513c8)

**Comment by dimasciput** [comment]
@vikineema this is now fixed
