### ISSUE TITLE
add option to duplicate a timesheet entry

### ISSUE THREAD

**Issue by gubuntu** [kartoza/timesheet-project#106]
often a timesheet entry is very similar to a previous one. In the ellipsis menu is yould be useful to have a 'Duplicate' option that creates a new entry in edit mode with all the same form content so the user can edit times, comments, etc. as appropriate and then save, without having to select and write everything from scratch

Sage and I'm sure Harvest had this functionality.

**Comment by dimasciput** [comment]
@gubuntu , this already exists in the app.

https://github.com/kartoza/timesheet-project/assets/1979569/fbaa3da5-f672-4a7e-99a6-a2a11e2e54b2

**Comment by gubuntu** [comment]
duh! good to know, thanks for pointing it out!
