### ISSUE TITLE
'clear submitted' not working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/timesheet-project#159]
I submitted these on 31 Oct. When I 'cleared submitted' today, all entries but these cleared. So I submitted again and tried clearing again to no avail. 
<img width="1298" alt="Screenshot 2024-11-04 at 11 56 36" src="https://github.com/user-attachments/assets/ad99aa66-56a5-4c8c-b7ac-64af22509d6f">

**Comment by dimasciput** [comment]
@gubuntu please refresh and then re-submit
