### ISSUE TITLE
timesheet entry won't submit

### ISSUE THREAD

**Issue by gubuntu** [kartoza/timesheet-project#167]
<img width="1356" alt="Screenshot 2024-11-22 at 20 52 42" src="https://github.com/user-attachments/assets/c1c88b7f-5899-493d-827c-a737db06f87a">

**Comment by dimasciput** [comment]
@gubuntu, this is usually because the task no longer exists in the erpnext. I noticed that 'Consulting' is no longer in erpnext. I have manually updated your task to 'Consulting November.' You can also update this on the timesheet. Please submit it now.

**Comment by gubuntu** [comment]
thanks Dimas. Whoops I forgot to update it in the app but it still submitted successfully. 

I wonder why it would have been an option if it didn't exist in the ERP
