### ISSUE TITLE
Add notes and fractional days option

### ISSUE THREAD

**Issue by timlinux** [kartoza/timesheet-project#59]
![image](https://github.com/kartoza/timesheet-project/assets/178003/3996d06f-3c21-4e1d-92ea-dd7e4daff891)

**Comment by timlinux** [comment]
![image](https://github.com/kartoza/timesheet-project/assets/178003/def17682-25c9-43c3-86c7-bd3ab22388c6)

**Comment by dimasciput** [comment]
both are added
