### ISSUE TITLE
The plan on timeline shifted

### ISSUE THREAD

**Issue by meomancer** [kartoza/timesheet-project#65]
# Problem
The plan in timeline shifted on timesheet.

I have public holiday on 1 june and 2 june, it is geosight
![Selection_027](https://github.com/kartoza/timesheet-project/assets/4530905/463ec18e-d394-4067-a06a-dc26aa2c3192)

But on timesheet, it is shifted
![Selection_026](https://github.com/kartoza/timesheet-project/assets/4530905/e8cf1db7-96e6-4363-9053-31a715548687)

The grid on 1 june does not exist (that why it is shifted)

**Comment by dimasciput** [comment]
This is fixed
