### ISSUE TITLE
Show time logging leaderboard

### ISSUE THREAD

**Issue by timlinux** [kartoza/timesheet-project#83]
![image](https://github.com/kartoza/timesheet-project/assets/178003/c47d9436-d328-41e3-ac38-4de8beda9c86)

**Comment by timlinux** [comment]
Also activity list

![image](https://github.com/kartoza/timesheet-project/assets/178003/d57008e0-441f-40a4-a9b0-7e58e7e56005)

**Comment by dimasciput** [comment]
This is done
