### ISSUE TITLE
[enhancement] Give text  an outline

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/timesheet-project#97]
The white text on a light color is hard to read.
![image](https://github.com/kartoza/timesheet-project/assets/107027990/6276a0a9-ac7a-4d83-9c6c-6ff19cd61227)

 Solution can be found in various different ways:
- Make text change color in relation to background color
- Give text a dark 1px or 2px stroke (outline). This should allow text to be readable regardless of the background color  (image below has 1px stroke)
![image](https://github.com/kartoza/timesheet-project/assets/107027990/5e0607d4-fc05-446a-81da-e99c16246481)

**Comment by dimasciput** [comment]
Hi @EliVolsch , is the text better now?

**Comment by EliVolsch** [comment]
Yes! thank you the text is much more readable regardless of the background color. 

![image](https://github.com/kartoza/timesheet-project/assets/107027990/4f6858eb-951c-427b-8b64-0022fd9014d5)
